token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJuZXdwYW5lIiwiZnVsbG5hbWUiOiJzYWdhciBuZXdwYW5lIiwiZXhwIjoxNzY4Mzc1NzM2fQ.pM9aU4qY6v3D2MRqgnvdCCsIdssdnfIpmZtbIukbZ8Y"

from auth import decode_token

user = decode_token(token)
print(user)
